version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio
    platform: linux/x86_64
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
